---
title: "Curriculum Vitae - Diego Alcaraz"
format: html
page-layout: full
---

<div class="cv-container">

<!-- LEFT COLUMN -->
<div class="left-column">

### CONTACT

**Diego Alejandro Zapata Alcaraz**  
Brisbane, Australia\
**Email:** diego080495\@gmail.com\
**Phone:** 0426 433 170\
**GitHub:** <https://github.com/diego-alcaraz>\
**LinkedIn:** <https://linkedin.com/in/diego-alcaraz->\


### TECHNICAL SKILLS

**Coding**  
Python, R, SQL, Julia, DAX, Latex

**Analytics & ML**  
Predictive Modelling  
Clustering  
Bayesian Stats  
Deep Learning  

**Tools**  
Jupyter, RStudio, PyCharm,
GA4, BigQuery, 
Power BI, Tableau
MS suite, Git, GitHub

**Methods**  
Agile, Lean, Six Sigma


### CERTIFICATIONS

• [Deep Learning (Coursera)](https://coursera.org/share/4425a51d5bb084480d9a6ec2ac51c9f3)\
• [Statistics with Python (Coursera)](https://coursera.org/share/8134291d4835d50c0b757a5e572bffba)\
• [Additional certifications available on Coursera profile](https://www.coursera.org/learner/diego-zapata-alcaraz)\
• [Australina Computer Society (ACS) accredited Data Science Professional](src/ACS_DataScientist.pdf)\


### INTERESTS

Craft beer brewing  • Cooking • Hiking  
Camping • Fitness  


</div>

<!-- RIGHT COLUMN -->
<div class="right-column">

## RESEARCH INTERESTS

Applied Machine Learning; Statistical Modelling; Clustering & Unsupervised Learning; Optimization for Data‐Driven Decision Making; Predictive Analytics; Consumer Behaviour Modelling; Bayesian Statistics.

## EDUCATION

**Bachelor of Science Data Science**  
*The University of Queensland*\
GPA: 6.75/7.00\
2025 – 2026*\

**Diploma in Analytics**  
*Universidad Nacional de Colombia*\
GPA: 4.90/5.00\
2019 - 2020\

**Bachelor of Science Industrial Engineering**  
*Universidad Nacional de Colombia*\
GPA: 4.30/5.00\
2013 - 2019\

## ACADEMIC EXPERIENCE

### **Differential Calculus tutor**
*Universidad Nacional de Colombia*\
*Feb 2017 – Jun 2018*\
- Provided one-on-one and group tutoring in limits, derivatives, optimisation, related rates, Taylor approximations, and multivariable calculus, improving students’ conceptual understanding and problem-solving skills.\
- Delivered tutorials and exam preparation sessions.\
- Helped students develop mathematical reasoning techniques, such as function analysis, algebraic manipulation, graphical interpretation, and real-world application of calculus concepts.\

## HONORS & AWARDS

- Dean's Commendation for Academic Excellence - The University of Queensland - Semester 1, 2025.\
- Colfuturo Scholarship for Academic Excellence at The University of Queensland - 2024.\
- Ranked 2nd over 57 in B.Sc. Industrial Engineering cohort.\
- Academic merit scholarship during B.Sc. Industrial Engineering - Semester 1, 2017.\
- Academic merit scholarship during B.Sc. Industrial Engineering - Semester 2, 2017.\
- 2nd place – Interacpedia Business Challenge: Reduction of organic waste throughout the paper manufacturing process.\


## PROFESSIONAL EXPERIENCE

### **Data Analyst — Conversion Kings**  
*Jan 2025 – Present*

- Conduct GA4 audits, identifying tracking gaps and measurement inconsistencies.\
- Deliver Baseline & User Journey Reports, analysing multi-device funnels and behavioural patterns.\
- Support A/B testing operations: MDI calculations, report validation, insights dashboards.\
- Produce Monthly & Quarterly CRO funnel reports using statistical anomaly detection.\

**Achievements:**

- Automated A/B test report workflows, reducing processing time from 1 hour to 10 minutes per test.
- Awarded Employee of the Month (Oct) for performance excellence.


### **Senior Data Scientist — Bancolombia Bank**  
*Jun 2021 – Sep 2023*

- Designed forecasting and ML models (including deep learning) for customer behaviour and financial risk.\
- Extracted, transformed, and analysed high-volume datasets for strategic insights.\
- Built dashboards and reporting systems to support real-time decision making.\
- Interacted with business stakeholders to define analytical needs.\

**Achievements:**

- Reduced service waiting time by 25% by optimising commercial resource allocation.\
- Developed a probability‐of-default model, lowering portfolio loss rates by 4%.\
- Created a customer‐level classification model enabling personalised offers.\

### **Assortment Data Analyst — Grupo Exito**  
*Mar 2019 – May 2021*

- Analysed product consumption patterns and developed insights dashboards.\
- Managed product assortment across 80 retail stores, improving stock allocation.\
- Created planograms to support commercial and operational strategies.\
- Applied statistical modelling to identify trends, substitutability, and assortment optimization.\

**Achievements:**

- Built a Bayesian model reducing excess stock by 15%.
- Fully automated the assortment optimization process.

---


## REFERENCES

Available upon request.

</div>

</div> <!-- end container -->
